
project_id = "cvcebcisijjmmmwuedcv"

[auth]
enabled = true
site_url = "https://a2978196-c5c0-456b-9958-c4dc20b52bea.lovableproject.com"
additional_redirect_urls = ["https://localhost:5173"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.send-group-notification]
verify_jwt = true
