
project_id = "cvcebcisijjmmmwuedcv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://senior-digital-mentor.com"

[analytics]
enabled = false

[realtime]
enabled = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.auth-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
