
project_id = "cvcebcisijjmmmwuedcv"

[auth]
enabled = true
site_url = "https://a2978196-c5c0-456b-9958-c4dc20b52bea.lovableproject.com"
additional_redirect_urls = ["https://localhost:5173"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.send-group-notification]
verify_jwt = true

[functions.send-content-notification]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.auth-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.process-invitation]
verify_jwt = true

[functions.sync-invitation-permissions]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-intervention-notification]
verify_jwt = true
